@extends('front.layout.main')
@section('content')
<div class="container">
<br>
	<div class="row-fluid">
		<div class="col-md-12" >
		<div class="panel panel-primary">
			<div class="panel-body">
				<div class="col-md-12">
					<h1 class="text-center text-danger">Icaps Tearms and Condition</h1>
					<hr>
					<p style="color:#000">Welcome to icaps.co.in.  ICAPS provides website features and other products and services to you when you visit or shop at icaps.co.in. </p>
					<p><b>This document is an electronic record in terms of Information Technology Act, 2000 and rules made there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
					This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and user agreement for access or usage of www.icaps.co.in  website. 
					</b></p>
					<p>ICAPS provides the Services subject to the following conditions.</p>
					<h4><b>By using ICAPS Services, you agree to these terms & conditions. Please read them carefully.</b></h4>
					<p>We offer a wide range of ICAPS Services, and sometimes additional terms may apply. When you use an ICAPS Service (for example, Your Profile, Gift Cards, Membership Offer,you also will be subject to the guidelines, terms and agreements applicable to that ICAPS Service ("Service Terms"). If these Conditions of Use are inconsistent with the Service Terms, those Service Terms will control.</p>
					<p>Our use of the Website and services and tools are governed by the following terms and conditions ("<b>Terms of Use</b>") as applicable to the Website including the applicable policies which are incorporated herein by way of reference. If you transact on the Website, You shall be subject to the policies that are applicable to the Website for such transaction. By mere use of the Website, You shall be contracting with www.icaps.co.in.</p>
					<p>For the purpose of these Terms of Use, wherever the context so requires <b>"You"</b> or <b>"User"</b> shall mean any natural or legal person who has agreed to become a buyer on the Website by providing Registration Data while registering on the Website as Registered User using the computer systems. I-CAPS allows the User to surf the Website or making purchases without registering on the Website. The term <b>"We"</b>, <b>"Us"</b>, <b>"Our"</b> shall mean I-CAPS Trade Solutions Private Limited</p>
					<p>When You use any of the services provided by Us through the Website, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use.</p>
					<p>We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Website following the posting of changes will mean that you accept and agree to the revisions. As long as you comply with these Terms of Use, We grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.</p>
					<h4><b>Your Account and Registration Obligations</b></h4>
					<p>If You use the Website, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Website and refuse to provide You with access to the Website.</p>
					<h4><b>Business entity registration:</b></h4>
					<p> If you are registering as a business entity, you represent that you are duly authorized to accept this User Agreement and you have the authority to bind your business entity to this User Agreement.</p>
					<h4><b>Guest User:</b></h4>
					<p>If you are transacting as a Guest User, you shall not be allowed to list/ sell product or services on Website and there could be certain additional restrictions on you as a Guest User for your purchase and the other functionality of the Website available to you.</p>
					<h4><b>FREE SHIPPING</b></h4>
					<ul>
						<li>Free shipping is applicable on selected products only</li>
						<li>Deal-based free shipping remains active for limited time period only</li>
						<li>Shipping charges may be reduced when products such as Televisions, Air Conditioners, Laptops, etc. are bought in bulk</li>
					</ul>
					<h4><b>Electronic Execution and Communications</b></h4>
					<p>When you use any I- CAPS Service, or send e-mails, text messages, and other communications from your desktop or mobile device to us, you are communicating with us electronically. You consent to receive communications from us electronically, such as e-mails, texts, mobile push notices, or notices and messages on this site or through the other ICAPS Services, such as our Message Center, and you can retain copies of these communications for your records. You agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</p>
					<h4><b>Platform for Communication</b></h4>
					<ul>
						<li>The Website is a platform that Users utilize to meet and interact with one another for their transactions. I- CAPS is not and cannot be a party to or control in any manner any transaction between the Website's Users.</li>
						<li>All commercial / contractual terms are offered by and agreed to between buyers and sellers alone. The commercial / contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties and after sales services related to goods and services. I- CAPS does not have any control or determines or advises or in any way involves itself in the offering or acceptance of such commercial / contractual terms between buyers and sellers.</li>
						<li>I- CAPS is not responsible for any non-performance or breach of any contract entered into between Buyers and Sellers. I – CAPS cannot and does not guarantee that the concerned Buyers and/or Sellers will perform any transaction concluded on the Website. I- CAPS shall not and is not required to mediate or resolve any dispute or disagreement between Buyers and Sellers.</li>
						<li>I- CAPS does not make any representation or warranty as to the item-specifics (such as legal title,creditworthiness, identity, etc) of any of its Users. You are advised to independently verify the bona fides of any particular User that you choose to deal with on the Website and use Your best judgment in that behalf.</li>
						<li>The Website is only a platform that can be utilized by Users to reach a larger base to buy and sell products or services. I- CAPS is only providing a platform for communication and it is agreed that the contract for sale of any of the products or services shall be a strictly bipartite contract between the Seller and the Buyer.</li>
						<li>You shall independently agree upon the manner and terms and conditions of delivery, payment, insurance etc. with the seller(s) that You transact with.</li>
						<li>Disclaimer: Pricing on any product(s) as is reflected on the Website may due to some technical issue, typographical error or product information published byseller may be incorrectly reflected and in such an event seller may cancel such your order(s).</li>
						<li>You release and indemnify I- CAPS and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the Users of the Website and specifically waive any claims that you may have in this behalf under any applicable law. Notwithstanding its reasonable efforts in that behalf, I- CAPS cannot take responsibility or control the information provided by other Users which is made available on the Website. You may find other User's information to be offensive, harmful, inconsistent, inaccurate, or deceptive. Please use caution and practice safe trading when using the Website.</li>
						<li>Please note that there could be risks in dealing with underage persons or people acting under false pretenses.</li>
					</ul>
					<h4><b>Charges</b></h4>
					<p>Membership on the Website is free for buyers. I- CAPS does not charge any fee for browsing and buying on the Website. I_ CAPS reserves the right to change its Fee Policy from time to time. In particular, I- CAPS may at its sole discretion introduce new services and modify some or all of the existing services offered on the Website. In such an event I- CAPS reserves the right to introduce fees for the new services offered or amend/introduce fees for existing services, as the case may be. Changes to the Fee Policy shall be posted on the Website and such changes shall automatically become effective immediately after they are posted on the Website. Unless otherwise stated, all fees shall be quoted in Indian Rupees. You shall be solely responsible for compliance of all applicable laws including those in India for making payments to I- CAPS Internet Private Limited.</p>
					<h4><b>Use of the Website</b></h4>
					<p>You agree, undertake and confirm that Your use of Website shall be strictly governed by the following binding principles:</p>
					<ol>
						<li>
						You shall not host, display, upload, modify, publish, transmit, update or share any information which
						<ol>
							<li>belongs to another person and to which You does not have any right to;</li>
							<li>is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation of women" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;</li>
							<li>is misleading in any way;</li>
							<li>is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, pedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;</li>
							<li>Harasses or advocates harassment of another person;</li>
							<li>Involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming";</li>
							lipromotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;
						</ol>
						</li>
						<li>You shall not use any "deep-link", "page-scrape", "robot", "spider" or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Website or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Website. We reserve Our right to bar any such activity.</li>
						<li>You shall not attempt to gain unauthorized access to any portion or feature of the Website, or any other systems or networks connected to the Website or tony server, computer, network, or to any of the services offered on or through the Website, by hacking, password "mining" or any other illegitimate means.</li>
						<li>You shall not probe, scan or test the vulnerability of the Website or any network connected to the Website nor breach the security or authentication measures on the Website or any network connected to the Website. You may not reverse look-up, trace or seek to trace any information on any other User of or visitor to Website, or any other customer, including any account on the Website not owned by You, to its source, or exploit the Website or any service or information made available or offered by or through the Website, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than Your own information, as provided for by the Website.</li>
						<li>You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about Us or the brand name or domain name used by Us including the terms I- CAPS, Flite, Digi flip I- CAPS.com, or otherwise engage in any conduct or action that might tarnish the image or reputation, of I- CAPS or sellers on platform or otherwise tarnish or dilute any I- CAPS's trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by us. You agree that You will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Website or I- CAPS's systems or networks, or any systems or networks connected to I- CAPS.</li>
						<li>You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Website or any transaction being conducted on the Website, or with any other person's use of the Website.</li>
						<li>You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal You send to Us on or through the Website or any service offered on or through the Website. You may not pretend that You are, or that You represent, someone else, or impersonate any other individual or entity.</li>
						<li>You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal You send to Us on or through the Website or any service offered on or through the Website. You may not pretend that You are, or that You represent, someone else, or impersonate any other individual or entity.</li>
						<li>You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules thereunder as applicable and as amended from time to time and also all applicable Domestic laws, rules and regulations (including the provisions of any applicable Exchange Control Laws or Regulations in Force) and International Laws, Foreign Exchange Laws, Statutes, Ordinances and Regulations (including, but not limited to Sales Tax/VAT, Income Tax, Octroi, Service Tax, Central Excise, Custom Duty, Local Levies) regarding Your use of Our service and Your listing, purchase, solicitation of offers to purchase, and sale of products or services. You shall not engage in any transaction in an item or service, which is prohibited by the provisions of any applicable law including exchange control laws or regulations for the time being in force.</li>
						<li>Solely to enable Us to use the information You supply Us with, so that we are not violating any rights You might have in Your Information, You agree to grant Us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights You have in Your Information, in any media now known or not currently known, with respect to Your Information. We will only use Your information in accordance with the Terms of Use and Privacy Policy applicable to use of the Website.</li>
						<li>From time to time, You shall be responsible for providing information relating to the products or services proposed to be sold by You. In this connection, You undertake that all such information shall be accurate in all respects. You shall not exaggerate or over emphasize the attributes of such products or services so as to mislead other Users in any manner.</li>
					</ol>
					<h4><b>Selling</b></h4>
					<p>As a registered seller, you are allowed to list item(s) for sale on the Website in accordance with the Policies which are incorporated by way of reference in this Terms of Use. You must be legally able to sell the item(s) you list for sale on our Website. You must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics and pictures that describe your item for sale. All listed items must be listed in an appropriate category on the Website. All listed items must be kept in stock for successful fulfilment of sales.</p>
					<p>The listing description of the item must not be misleading and must describe actual condition of the product. If the item description does not match the actual condition of the item, you agree to refund any amounts that you may have received from the Buyer. You agree not to list a single product in multiple quantities across various categories on the Website. I- CAPS reserves the right to delete such multiple listings of the same product listed by you in various categories.</p>
					<h4><b>Polices</b></h4>
					<h5><b>Use of Personal Information</b></h5>
					<p>Visitors to our website can register to purchase services. When you register, we will request some personal information such as name, address, email, telephone number or facsimile number, account number and other relevant information. If you are purchasing a service, we will request financial information. Any financial information we collect is used only to bill you for the services you requested and/or purchased and any applicable fees that are compliant with our Terms of Use. If you purchase by credit card, the information may be forwarded to your credit card provider. For other types of registrations, we will ask for the relevant information. You may also be asked to disclose personal information to us so that we can provide assistance and information to you. For example, such data may be warranted in order to provide online technical support and troubleshooting. Under some circumstances we may require some additional financial information, including, without limitation, your billing address, bank account information, and tracking information from checks or money orders. We will not disclose personally identifiable information we collect from you to third parties without your permission except to the extent necessary including:</p>
					<ul>
						<li>To fulfill your service requests for services,</li>
						<li>To protect ourselves from liability,</li>
						<li>To respond to legal process or comply with law, or</li>
						<li>In connection with a merger, acquisition, or liquidation of the company.</li>
					</ul>
					<p>Please note that we will use your information and other information we obtain from your current and past activities on the site to resolve any disputes, troubleshoot problems, collect fees owed, pay amounts due you, or verify your account data. We employ many different security techniques to protect any personal data from unauthorized access by users inside and outside the company, however please be aware that "perfect security" does not exist on the Internet or with any digital or physical data.</p>
					<h5><b>Replacement Guarantee*</b></h5>
					<p>The Replacement Guarantee seeks to assist Buyers who have been defrauded by qualified sellers on the Website. If at the time of delivery and/or within specified days from the date of delivery of the product/s, if any defect is found, then the buyer of the product/s can ask for replacement of the product/s from the seller.</p>
					<p>If M has suspicion or knowledge, that any of its buyers and sellers are involved in any activity that is intended to provide claims or information that is false, misleading or not genuine, then I- CAPS may while reserving its rights to initiate civil and/or criminal proceedings against User may also at its sole discretion suspend, block, restrict, cancel the Display Name of such buyer and seller and /or disqualify that User and any related Users from availing protection through this program.</p>
					<p>I-CAPS reserves its right to initiate civil and/or criminal proceedings against a User who, files a invalid and/or false claims or provides false, incomplete, or misleading information. In addition to the legal proceedings as aforesaid, I- CAPS may at its sole discretion suspend, block, restrict, cancel the Display Name [and its related Display Names] of such User and/or disqualify that User and any related Users from availing protection through this program. Any person who, knowingly and with intent to injure, defraud or deceive, files a Fraudulent Complaint containing false, incomplete, or misleading information may be guilty of a criminal offence and will be prosecuted to the fullest extent of the law.</p>
					<h5><b>Returns Policy</b></h5>
					<p>Definition: 'Return' is defined as the action of giving back the item purchased by the Buyer to the Seller on the I –CAPS website. Following situations may arise:</p>
					<ol>
						<li>Item was defective</li>
						<li>Item was damaged during the Shipping</li>
						<li>Products was / were missing</li>
						<li>Wrong item was sent by the Seller.</li>
					</ol>
					<p>Return could also result in refund of money in most of the cases. Points to be noted:</p>
					<ol>
						<li>Seller can always accept the return irrespective of the policy</li>
						<li>If Seller disagrees a return request, Buyer can file a dispute under the Buyer Protection Program*.</li>
					</ol>
					<p>We encourage the Buyer to review the listing before making the purchase decision. In case Buyer orders a wrong item, Buyer shall not be entitled to any return/refund. Buyer needs to raise the return request within the return period applicable to the respective product. Once Buyer has raised a return request by contacting us on Our Toll Free Number, Seller while closing the return ticket can select one of the following:</p>
					<ol>
						<li>Replace after shipment collection - Seller has agreed to wait for the logistics team to collect the shipment from the buyer before replacing it)</li>
						<li>Refund after shipment collection - Seller has agreed to wait for the logistics team to collect the shipment from the buyer before refunding)</li>
						<li>Refund without shipment collection - Seller has agreed to refund the buyer without expecting the original shipment back)</li>
						<li>Replace without shipment collection - Seller has agreed to replace the order without expecting the original shipment back)</li>
					</ol>
				</div>
			</div>
		</div>
			
		</div>
	</div>
<br>
</div>

@endsection